### ISSUE TITLE
undefined method `code'

### ISSUE THREAD

**Issue by malshami** [rapid7/nexpose_ticketing#10]
Hello there, 

I was finally able to install everything and it seems to be working and creating tickets. but in the process of creating tickets ti gives me this error:

ruby nexpose_ticketing jira
/home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/helpers/jira_helper.rb:189:in `block in create_tickets': undefined method `code' for nil:NilClass (NoMethodError)
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/helpers/jira_helper.rb:180:in `each'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/helpers/jira_helper.rb:180:in `create_tickets'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:229:in `ticket_rate_limiter_processor'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:272:in `ticket_rate_limiter'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:162:in `block in all_site_report'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:157:in `each'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:157:in `all_site_report'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:306:in `full_scan'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing/ticket_service.rb:293:in `start'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/nexpose_ticketing-1.2.1/lib/nexpose_ticketing.rb:8:in `start'
	from nexpose_ticketing:45:in `<main>'

Although it creates SOME tickets (not all) it does not sync so if I run it again it will recreate the same ticket for the same host although the mode is set to IP.

Any help is really appreciated.

**Comment by aRobinson-R7** [comment]
Hi @malshami 
We discovered this issue a while back when testing.
We have got a fix for this issue - hoping to release it onto rubygems by the end of the week.
:D
