### ISSUE TITLE
Missing checks for nil in v1.4.1

### ISSUE THREAD

**Issue by peterjmcg** [rapid7/nexpose_ticketing#16]
Several occurrences of "undefined method `[]' for nil:NilClass (NoMethodError)" . Added checks for nil:

**ticket_repository / initial_scan_by_ip**

next if (risk_score < (options[:riskScore] || 0)) || (info_hash[asset_id] == nil)

**ticket_repository / initial_scan_by_vuln_id**

if soln_ref_hash[vuln_id] == nil
				sids = ""
				refs = ""
			else
				sids = soln_ref_hash[vuln_id][:solution_ids]
				refs = soln_ref_hash[vuln_id][:refs]
			end
		  
          csv << [vuln_id, data[:vuln], vuln_def.title, vuln_def.cvss_score,
                  assets.join('~'), vuln_def.description,
                  sids,
                  refs]

**ticket_repository / generate_delta_csv_by_vuln_id**

if info[vuln_id] == nil
				sids = ""
				refs = ""
			else
				sids = info[vuln_id][:solution_ids]
				refs = info[vuln_id][:refs]
			end
            csv << [vuln_id, vuln, vuln_def.title, vuln_def.cvss_score,
                    assets.join('~'), vuln_def.description,
					
                    sids, refs, 'New']

May be more.

**Comment by aRobinson-R7** [comment]
Hi @peterjmcg 
This issue was brought to our attention soon after the last release.
We have implemented a fix:
https://github.com/rapid7/nexpose_ticketing/pull/17/files

It seems the reporting model we were using in Nexpose did not support having a discovery scan as the most recent scan for an asset / site.
Please advise if this new version does not resolve that. :)

**Comment by markmjr** [comment]
Hello,
I'm seeing the same type of behavior with 1.5.2

> /ticket_repository.rb:173:in "block (3 levels) in initial_scan_by_ip": undefined method `[]' for nil:NilClass (NoMethodError)

I enabled debug logging and I see it start going through getting vulns for systems:

> I,   INFO -- : Logging enabled at level <info>
I,   INFO -- : Current Encoding set to: UTF-8
I,   INFO -- : Logging enabled at level <debug>
I,   INFO -- : Loading IP mode dependencies.
I,   INFO -- : Getting vuln info for site: 10
I,   INFO -- : Creating query request "all_new_vulns_by_ip".
D,  DEBUG -- : Getting assets for 10
D,  DEBUG -- : Creating CSV for helper
D,  DEBUG -- : Getting vulns for asset x.x.x.x
D,  DEBUG -- : Getting vulns for asset x,x,x,x

Any thoughts?

**Comment by aRobinson-R7** [comment]
Hi @markmjr 
Can you give us some more information about the site you were trying to generate tickets for please?
Has it been scanned before?
Was the last scan a discovery scan?
Have any new assets been added, but not scanned?

Trying to narrow down the cause of the issue :)
Thanks

**Comment by markmjr** [comment]
Hello @aRobinson-R7 
I have a small site of 8 systems used for this testing.
I performed an exhaustive scan on it prior to testing the gem.
No new assets were added after the exhaustive scan and before running the gem.
I also have a support ticket into Rapid7. If it makes more sense to work on this with them at this time, that's fine, and I can come back here if needed.
Thanks.

**Comment by aRobinson-R7** [comment]
Hi @markmjr 
Did this issue resolve itself?
I believe you had been in contact with support, but there was no longer an issue?
