### ISSUE TITLE
Error while running Run the nexpose_ticketing file

### ISSUE THREAD

**Issue by cmotukuri** [rapid7/nexpose_ticketing#19]
![screen shot 2017-05-03 at 2 06 23 pm](https://cloud.githubusercontent.com/assets/26581061/25901948/31cf875c-3566-11e7-8c78-15556e32d325.png)

Any one experienced similar error during the setup?

Any input helps.

**Comment by dvalente-r7** [comment]
Hello,
This means that the Ruby YAML parser is having trouble reading the JIRA configuration file. This generally occurs when an error is made during set-up.

Compare your config to the default one that ships with the gem:
[](https://github.com/rapid7/nexpose_ticketing/blob/master/lib/nexpose_ticketing/config/jira.config)

You may want to try placing `'` characters around any values containing non-alphanumeric characters.

If you're still having issues, please contact support@rapid7.com with the gem logs, the stack trace and the configuration files (with sensitive details removed).

**Comment by cmotukuri** [comment]
Thanks. I placed ' characters around  non-alphanumeric.

But I received one more error.

![screen shot 2017-05-10 at 10 45 54 am](https://cloud.githubusercontent.com/assets/26581061/25904824/5ac7f09c-356e-11e7-8a72-54888bf74ee6.png)

I also checked config with default one. 

My config:

---

# This configuration file defines all the particular options necessary to support the helper.

# Fields marked (M) are mandatory.
#
# (M) Product name
:product: JIRA
# (M) Vendor
**:vendor: Atlassian** -- Line 8 
# (M) Helper class name.
:helper_name: JiraHelper
# Optional parameters, these are implementation specific.

**Comment by dvalente-r7** [comment]
It's difficult to diagnose without the context of the entire configuration file. Please contact support@rapid7.com with the gem logs, the stack trace and entire configuration files (with sensitive details removed).

In the mean time, you may wish to use a service such as [http://www.yamllint.com/](http://www.yamllint.com/) to validate your config, with sensitive details removed.

**Comment by cmotukuri** [comment]
Ok thanks. I will contact for troubleshooting. 
I have one more question.

in jira_config:
for jira_url -- do we have use just the https://base url or do we have to replace base url in https://url/rest/api/2/issue ?

Ex: **https://jira.company.com/** or **https://jira.company.com/rest/api/2/issue/** ??

-Chandrika

**Comment by dvalente-r7** [comment]
It must include the `rest/api/2/issue` section so it can access the endpoint.

**Comment by cmotukuri** [comment]
thanks.

**Comment by cmotukuri** [comment]
Hi,

I was able to solve almost all the errors but stuck with this particular one . Have you ever seen this kind of error? 

![screen shot 2017-05-11 at 1 13 52 pm](https://cloud.githubusercontent.com/assets/26581061/25962550/2a6ed1b6-364c-11e7-9ea7-69b7484dd12a.png)

**Comment by peterjmcg** [comment]
I think I have seen this when using Remedy because the ticket server was busy and took a long time to respond. I worked around it by changing the wait time in the Nexpose gem report.rb, method generate from 300 sec to 600 sec (or whatever value works for you).

**Comment by cmotukuri** [comment]
I tried increasing the time out value. But it did not work.

**Comment by dvalente-r7** [comment]
You may see an error such as this if the url provided in the config is incorrect:
It should in the format:

`:jira_url: https://instance.atlassian.net/rest/api/2/issue/`

If a port is necessary, make sure this is also provided:

`:jira_url: 127.0.0.1:8080:/rest/api/2/issue`
