### ISSUE TITLE
nexpose_ticketing issue unknown

### ISSUE THREAD

**Issue by namanrg** [rapid7/nexpose_ticketing#22]
C:\RailsInstaller\Ruby2.3.0\lib\ruby\gems\2.3.0\gems\nexpose_ticketing-1.5.2\bin
>nexpose_ticketing servicenow
C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/ffi-1.9.18-x86-mingw32/lib/
ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': The
 (LoadError)dule could not be found.

**Comment by aRobinson-R7** [comment]
Hi @namanrg 
We use a Ruby gem called `typhoeus` in this project, which requires Libcurl to be installed on your system for sending and receiving HTTP requests.
- Linux and Mac OS can download this via a package manager.
- For Windows machines it has to be downloaded from the publishers website.

You will need to download the correct version for your OS

**Comment by namanrg** [comment]
Here is an error i still face , please help on this
![image](https://user-images.githubusercontent.com/28726043/31355757-28815764-ad59-11e7-8af2-460a61a37f2a.png)

**Comment by aRobinson-R7** [comment]
Hi @namanrg 

This looks like a SSL certificate issue when trying to push data to your ServiceNow instance - it's being refused because you are not providing a certificate.
Can you check the `servicenow_url` value in the servicenow.config file?
You may be able to bypass it by removing the "S" in "https" from the URL string in your servicenow.config file.

**Comment by namanrg** [comment]
Hi @aRobinson-R7 

Thanks for the response , the errors seem to be fixed but i am not sure why the tickets in servicenow are not getting created. Sharing with you  the logs.
The update set has been retrieved and i guess that is fine . i hope the logs help.

[ticket_service.log](https://github.com/rapid7/nexpose_ticketing/files/1373037/ticket_service.log)
[rapid7_integration.log](https://github.com/rapid7/nexpose_ticketing/files/1373038/rapid7_integration.log)
[rapid7_incidentresponse_1.5.2.log](https://github.com/rapid7/nexpose_ticketing/files/1373039/rapid7_incidentresponse_1.5.2.log)

**Comment by aRobinson-R7** [comment]
@namanrg 
Looking at the logs, it looks like a full run of the integration succeeded (it may have not sent tickets, but it ran from start to finish).
This will have created a file called last_scan_data.csv under _<nexpose_ticketing_install_location>/lib/nexpose_ticketing/_
If you remove or rename (safer) this file, you can run the integration again, as if for the first time. It stores information about the last run of the integration and will only create tickets for sites with a new scan since the last run.
It still looks like you may be experiencing the SSL issue (around 2.02 on 10/10 in the incidentResponse log)

**Comment by namanrg** [comment]
@aRobinson-R7 
First of all , thanks alot for the help. I still have a few errors sharing those with you.
For the SSL issue i removed the 'S' from the servicenow config file in the url but i now get the HTTP 302 error.  
![image](https://user-images.githubusercontent.com/28726043/31584459-aa20dffc-b1cc-11e7-8e55-6b024578e27b.png)

**Comment by namanrg** [comment]
To add, i have resetup the whole thing, it doesnt create the last_scan_data file as of now i guess it would create it this error is cleared

**Comment by namanrg** [comment]
@aRobinson-R7 

Would you know why do i get the ssl connect error? and what file does it come from?

**Comment by aRobinson-R7** [comment]
Hi @namanrg,
The last_scan_data.csv is only ever created at the end of a **_successful_** run, so until the SSL issue is resolved it won't appear.
I imagine that 'your' ServiceNow instance may not allow you to POST data via HTTP and is trying to redirect you to the HTTPS endpoint.
However, if you insert the following code, this will allow you to see what the body of the request says and we can confirm what endpoint it wants you to work with.

In the servicenow_helper.rb file, line 236, insert this after `@log.log_error_message msg`
- `@log.log_error_message response.body`

This will print out the body with the redirect information

**Comment by aRobinson-R7** [comment]
If you need to use SSL / certificates, you could modify the code like this example:
[Adding SSL to Typhoeus request (from StackOverflow)](https://stackoverflow.com/questions/5147388/switching-an-ssl-configuration-from-my-computer-to-an-hosting-server)

We currently use the `ssl_verifyhost` option, so the integration does not check the Cert provider matches the certificate.
You could try adding one of the following options (but not at the same time):
- `ssl_verifypeer: false` (disables verification of peers cert)
- follow the information in [this issue](https://github.com/typhoeus/typhoeus/issues/441), where they discuss how to correctly setup Certificates on the users machine to work with the Typhoeus gem.

You will need to add either of the flags to the options hash (I believe) in two locations in the servicenow_helper.rb file. We do however not recommend this:
- [Post Requests](https://github.com/rapid7/nexpose_ticketing/blob/master/lib/nexpose_ticketing/helpers/servicenow_helper.rb#L260)
- [Identifier Requests](https://github.com/rapid7/nexpose_ticketing/blob/master/lib/nexpose_ticketing/helpers/servicenow_helper.rb#L275)

**Comment by namanrg** [comment]
Ok , yup i put the log you advised and i get this error

peer certificate cannot be authenticated with known CA certificates

**Comment by namanrg** [comment]
So now i did the ssl_verifypeer: false in the servicenow helper file.

I get no errors now but get no tickets into servicenow for now  .  i have attached the logs here. please help on this. 

Regards,
Naman
[ticket_service.log](https://github.com/rapid7/nexpose_ticketing/files/1402343/ticket_service.log)
[rapid7_incidentresponse_1.5.2.log](https://github.com/rapid7/nexpose_ticketing/files/1402344/rapid7_incidentresponse_1.5.2.log)
[rapid7_integration.log](https://github.com/rapid7/nexpose_ticketing/files/1402345/rapid7_integration.log)

**Comment by namanrg** [comment]
i get the messages from the metrics file on create update but donot get the tickets in servicenow. i guess some of the functions in the helper are having issues but not sure.

**Comment by aRobinson-R7** [comment]
Hi @namanrg 
You appear to still be getting the certificate issue - so the vulnerabilities are taken from InsightVM, converted into tickets, but then fail to send to ServiceNow itself.
From the combination of the error message and having tried the `ssl_verifypeer` change, it seems you will have to pass a valid certificate to your ServiceNow instance to be able to post data.

You should remove the `ssl_verifypeer` section you have just added and try to implement the certificate fix found in the links I sent you before.
I have not tried this myself, but the options are available to insert when creating the Typhoeus request.

**Comment by namanrg** [comment]
I am right now doing this using the Developer instance provided by servicenow , i believe that would have a valid certificate as its their own instance.

One thing that i was wondering is where is the rest api being called? i am trying to find where is the rest api and where is it being called.

**Comment by namanrg** [comment]
Hi Adam, 

I downloaded the Servicenow Certificate and copied it to the ssl folder , replacing it with the downloaded one. i still get the attached issue . can you tell me what does the 'block in ' mean here?
thanks & Regards,
Naman

![image](https://user-images.githubusercontent.com/28726043/32278242-180809fc-bf3b-11e7-9172-33ebbf3b9f27.png)

**Comment by aRobinson-R7** [comment]
Hi @namanrg 
A "block" is a Ruby concept - basically a piece of code, that in this case is stored and then run at a later point.
"True" isn't a valid value here, which may suggest you have modified something incorrectly..........
At this point it should be creating an "on_complete" action for when the request returns, so "True" should not be present.

As I said before I haven't seen this issue before.
If you have tried the options above, can you ensure that the account you are using has the correct privileges to insert data onto the incident table and you have the correct URL in the config?
`https://<your_servicenow_url>/u_rpd_vulnerabilities.do?JSONv2`

**Comment by namanrg** [comment]
yup the url and the credentials seem to be correct, what port of nexpose server does the data go from nexpose to servicenow . i was looking at the nexpose server and i saw no action on it using a tcp dump while i was running the ticketing system . i am assuming there are no packets being sent and there is something wrong on the nexpose end itself.
