### ISSUE TITLE
 SITE_VIEW for sites 1 (Nexpose::APIError)

### ISSUE THREAD

**Issue by jaishan** [rapid7/nexpose_ticketing#26]
Hi I am getting the following error 

$ ruby nexpose_ticketing servicenow
Still waiting. Current status: Started
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/report_helper.rb:39: warning: constant ::TRUE is deprecated
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/api_request.rb:146:in `execute': NexposeAPI: Action failed: User 46 does not have privileges SITE_VIEW for sites 1 (Nexpose::APIError)
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/connection.rb:118:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/site.rb:43:in `site_scan_history'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/site.rb:62:in `last_scan'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:671:in `block (2 levels) in load_last_scans'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:670:in `each'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:670:in `block in load_last_scans'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/csv.rb:1183:in `generate'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:668:in `load_last_scans'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:335:in `full_scan'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:310:in `start'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing.rb:8:in `start'
        from nexpose_ticketing:53:in `<main>'

Can anyone help

**Comment by dvalente-r7** [comment]
Please see the following error from your stack trace:

> User 46 does not have privileges SITE_VIEW for sites 1

This suggests that the user does not have sufficient privileges for executing queries against the selected site. You will need to adjust the user's roles within the Administration screen.

If you are still experiencing errors, please contact support@rapid7.com

**Comment by jaishan** [comment]
The user is global administrator role. I am not able to understand why its still showing this

**Comment by dvalente-r7** [comment]
Please contact support@rapid7.com so they may assist you further.

**Comment by jaishan** [comment]
can you let me know where this site_view class will be called.

**Comment by peterjmcg** [comment]
It's possible you are trying to access a site whose site ID no longer exists or has changed. Check if site ID = 1 still exists.

**Comment by jaishan** [comment]
Can you let me know on the ticket_service.config file in nexpose ticketing what should i configure. Below is one what i can see now. 

# This configuration file defines all the particular options necessary to run the service.^M
# Fields marked (M) are mandatory.^M
#^M
# Service options:^M
:options:^M
  # (M) Enables logging to the log directory.^M
  :logging_enabled: true^M
  # (M) Sets the log level threshold for output.^M
  :log_level: info^M
  # Enables logger output to console.^M
  :log_console: false^M
  # Filters the reports to specific sites one per line, leave empty for no site.^M
  :sites:
   - '1'

**Comment by jaishan** [comment]
![image](https://user-images.githubusercontent.com/14957392/34768407-be2204fc-f620-11e7-8078-c8092a94c810.png)

**Comment by jaishan** [comment]
What should i have to put to on the site value for all the sites? Is it * or something. please let me know.

**Comment by aRobinson-R7** [comment]
> # Filters the reports to specific sites one per line, leave empty for no site.
If you remove the line with the `-` it should work for all sites

**Comment by dvalente-r7** [comment]
If you continue to experience errors, our support team is available at support@rapid7.com

**Comment by jaishan** [comment]
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/bin$ ruby nexpose_ticketing servicenow
Still waiting. Current status: Started
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/report_helper.rb:39: warning: constant ::TRUE is deprecated
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/api_request.rb:146:in `execute': NexposeAPI: Action failed: User 1 does not have privileges SITE_VIEW for sites 1 (Nexpose::APIError)
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/connection.rb:118:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/site.rb:43:in `site_scan_history'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose-5.3.2/lib/nexpose/site.rb:62:in `last_scan'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:671:in `block (2 levels) in load_last_scans'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:670:in `each'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:670:in `block in load_last_scans'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/csv.rb:1183:in `generate'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_repository.rb:668:in `load_last_scans'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:335:in `full_scan'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:310:in `start'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing.rb:8:in `start'
        from nexpose_ticketing:53:in `<main>'


Same error !! I am thinking there could be issue with calling one ruby function from one directory to another.  Any other clues guys.

**Comment by dvalente-r7** [comment]
The error is being returned by Nexpose, so it does not appear to be a Ruby error.
This may be a configuration issue e.g. site with an ID of `1` does not exist, user does not have correct permissions or roles.

Our support team is available at support@rapid7.com
