### ISSUE TITLE
"I" mode no longer fully populates last_scan_data.csv

### ISSUE THREAD

**Issue by p4gs** [rapid7/nexpose_ticketing#4]
Looks like there's an issue with ticket_repository.rb on line 74. When I change it to read like below, last scan data starts to be populated in the CSV file. Otherwise, as it currently stands that file is created but only contains column headers and nothing else.

--Broken--
Line 74:  if sites.include? row.to_s[0]

--Fixed?--
Line 74:  if sites.include? row[0]

**Comment by JJCassidy-R7** [comment]
Yes, you will get duplicate tickets if the last_scan_date.csv file has no scan history stored within it.

We don't have any defects on file and I was not able to reproduce this on either Windows or Linux. Can you contact integrations_support[at]rapid7[.][com] with details surrounding this (OS, GEM versions, Ruby version, log files etc) and I'll pick it up and investigate further.
